### ISSUE TITLE
ScriptRunnerType.Yarn not working

### ISSUE THREAD

**Issue by agentschmitt** [EEParker/aspnetcore-vueclimiddleware#10]
I tried to use yarn instead of npm as scriptrunnertype under windows. And found out it is not working ;)
I get message: Usage: npm <command>after dotnet run.

My Configuration:
spa.UseVueCli(npmScript: "serve", port: 8080, regex: "Compiled ", runner: ScriptRunnerType.Yarn);

I think i found the related code where npm is used hard coded even when yarn is configured:
https://github.com/EEParker/aspnetcore-vueclimiddleware/blob/master/src/VueCliMiddleware/Util/ScriptRunner.cs:53
completeArguments = $"/c npm {completeArguments}";

**Comment by EEParker** [comment]
It is currently not fully implemented in the nuget version which is a little behind the code.

**Comment by sshanzel** [comment]
Hi! has this been implemented?

**Comment by EEParker** [comment]
I _think_ this has been fixed for 3.1 LTS version. There are a few other changes like the forceKill that could probably be backported to 2.2. 

However, I would like to point out that dotnet 2.2 has been EOL by Microsoft as of 2019-12-23.
https://github.com/dotnet/core/blob/master/microsoft-support.md#out-of-support-net-core-releases

**Comment by sshanzel** [comment]
Thanks a lot for mentioning that. Guess we gonna be migrating to 3.1
