### ISSUE TITLE
Use with https

### ISSUE THREAD

**Issue by dyesdyes** [EEParker/aspnetcore-vueclimiddleware#11]
Hey, I feel like there is a problem when using https locally.

Here is how I configured the project in startup:

```
app.UseHttpsRedirection();
app.UseStaticFiles();
app.UseSpaStaticFiles();
app.UseSpa(spa =>
{
    spa.Options.SourcePath = "ClientApp";

    if (env.IsDevelopment())
    {
        spa.UseVueCli(npmScript: "serve", port: 8085);
    }
});
```
It then keeps trying to Get on https://10.0.1.36:8085/sockjs-node/info, but the https address doesn't exist.
However, if I do a GET on http://10.0.1.36:8085/sockjs-node/info (http, not https), then it responds correctly.

How can i fix this ?

See the errors I get in the screenshot.

![screenshot](https://user-images.githubusercontent.com/1426272/53162285-fb2a5700-35cb-11e9-8ae7-3599570e326c.png)

**Comment by EEParker** [comment]
Is this the same as #9?

**Comment by dyesdyes** [comment]
Yes sorry, I got confused. It is the same !
