### ISSUE TITLE
Multipages

### ISSUE THREAD

**Issue by krumal** [EEParker/aspnetcore-vueclimiddleware#118]
Hello.
How to make?
i have "ClientApp/dist/index1.html" and "ClientApp/dist/index2.html"
need that url "site.com/service" use "index1.html"
url "site.com/otherservice" use "index2.html"
Thanks

**Comment by EEParker** [comment]
You have to use Map or MapWhen to set up multiple aspnetcore pipelines. 
https://stackoverflow.com/questions/56482398/how-to-handle-multiple-spa-application-in-asp-net-core
