### ISSUE TITLE
Webpack dev server not shutting down properly after debugging stops

### ISSUE THREAD

**Issue by oshawa-connection** [EEParker/aspnetcore-vueclimiddleware#123]
I've noticed that when I stop debugging my project, the webpack dev server keeps running.

This can result in the webpack dev server "detaching" from the one running in ASP. When this happens, changes to code still work, but it stops compiling changes to TypeScript interfaces and types. So I'll add a method to an interface, implement it, then try to call it. My regular webpack dev server builds and runs it fine, but the "detached" webpack dev server doesn't pick up the changes and displays a build error.

It is also an issue when switching between different projects using this library.

Restarting my computer, or ending all Node processes on my PC does fix the issue, but it is far from ideal. I don't have this issue with Angular or React.

**Comment by nikriaz** [comment]
same to me. Any solution?

**Comment by EEParker** [comment]
Have you tried the force kill option?

**Comment by nikriaz** [comment]
No, I don't know how to do that. Should I put this option to one of config files? Could you please advise?

**Comment by EEParker** [comment]
```csharp
endpoints.MapToVueCliProxy(
                    "{*path}",
                    new SpaOptions { SourcePath = "ClientApp" },
                    npmScript: (System.Diagnostics.Debugger.IsAttached) ? "serve" : null,
                    regex: "Compiled successfully",
                    forceKill: true // enable this to attempt to kill debug server
                    );
```
Use the above parameter `forceKill`.

**Comment by nikriaz** [comment]
Oh, this option was in your Vue3 sample I work with so it was enabled. It seems it doesn't work.

**Comment by nikriaz** [comment]
It looks like dev server stops to work as intended. Just need some time to stop, few seconds.

**Comment by oshawa-connection** [comment]
Hi, sorry for my late response, I totally forgot about this. I haven't tested out with the force kill option but I assume it fixes the issue as @nikriaz mentions.

cheers
