### ISSUE TITLE
Logging not working properly

### ISSUE THREAD

**Issue by gortibaldik** [EEParker/aspnetcore-vueclimiddleware#127]
Hi, I see in /src/VueCliMiddleware/Util/ScriptRunner.cs that when passing logger to AttachToLogger, the script still writes with Console.WriteLine, therefore there is no possible configuration of the logger which could turn off e.g. webpack script messages.

I suggest substituting Console.WriteLine with logger.LogInformation and logger.LogError.

**Comment by BinaryConstruct** [comment]
I have addressed this with the v6.0.0 packages.

**Comment by EEParker** [comment]
The v6.0.0 has included changes to address this. https://github.com/EEParker/aspnetcore-vueclimiddleware/commit/c04918e0d993ef101f962075458b3949c4a8fe13#diff-bde8369a4bd7e3d701d2946100729b99fa80b688dcb832b8a9ca95807793badaR142
