### ISSUE TITLE
dotnet 6.0

### ISSUE THREAD

**Issue by nick-orr** [EEParker/aspnetcore-vueclimiddleware#128]
@EEParker What's the status on making the project compatible with dotnet 6.0? Would you be open to allowing me to contribute to this project?

**Comment by EEParker** [comment]
Absolutely! I haven't had time to work on this for dotnet 6.0 yet, but I would gladly accept pull requests.

**Comment by sslaws** [comment]
Any idea on when the updated package will be available @EEParker?

**Comment by EEParker** [comment]
> 
> 
> Any idea on when the updated package will be available @EEParker?

It should be available once nuget finishes indexing it.

**Comment by TobbenTM** [comment]
The new .Net 6.0 release also changes the preferred way to host SPAs during development, using the SPA dev server to proxy requests to the backend instead, could it be an idea to align with that approach in this library too?

https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-net-6-preview-4/#improved-single-page-app-spa-templates

New nuget package for hosting here: https://www.nuget.org/packages/microsoft.aspnetcore.spaproxy

**Comment by BinaryConstruct** [comment]
I haven't gone through all the new changes, but there look to be several new features that might make this library unnecessary. However, as for right now keeping it up to date with minimal changes will ease migration.

For example, you can now have an SPA as the primary host, and the backend of the SPA will reverse proxy to the dotnet api. The new SPA packages also are providing first-class support for Vue, which is great! 

I will keep an eye on these changes and see where this library can be adapted to fit into the new ecosystem.

**Comment by EEParker** [comment]
@TobbenTM  I haven't gone through all the new changes, but there look to be several new features that might make this library unnecessary. However, as for right now keeping it up to date with minimal changes will ease migration.

For example, you can now have an SPA as the primary host, and the backend of the SPA will reverse proxy to the dotnet api. The new SPA packages also are providing first-class support for Vue, which is great!

I will keep an eye on these changes and see where this library can be adapted to fit into the new ecosystem.
