### ISSUE TITLE
I am getting npm error. missing script:"quasar"

### ISSUE THREAD

**Issue by mansurdegirmenci** [EEParker/aspnetcore-vueclimiddleware#140]
I'm using quasar version 2.5.3 and I couldn't get the project up and running. I am getting the error in the photo. It works via cmd but not via "asp.net core".

![image](https://user-images.githubusercontent.com/38755096/153031127-7463de9c-b6e2-46bf-83f3-ec165757036d.png)

**Comment by EEParker** [comment]
This command is actually executing `npm quasar serve`. If you add `quasar serve` to your package.json commands it will be compatible with this proxy launcher.

**Comment by EEParker** [comment]
For example: https://github.com/EEParker/aspnetcore-vueclimiddleware/blob/master/samples/QuasarCliSample/ClientApp/package.json#L10

**Comment by mansurdegirmenci** [comment]
I corrected the "regex" statement and did the package.json as you said and it was successful. thanks.
