### ISSUE TITLE
Websocket warning

### ISSUE THREAD

**Issue by jsodeman** [EEParker/aspnetcore-vueclimiddleware#17]
I'm not sure where in the tool chain this warning is coming from but I'm getting the following warning in the console when I start up the core app.

sockjs.js?9be2:2998 WebSocket connection to 'ws://localhost:65043/sockjs-node/439/hfyqih4v/websocket' failed: WebSocket is closed before the connection is established.

If that's coming from the Vue CLI or Visual Studio let me know and I'll open an issue there.

**Comment by EEParker** [comment]
That sounds like the visual studio debugger to me. Perhaps something is causing the service not to start?
