### ISSUE TITLE
There are two nuget packages?

### ISSUE THREAD

**Issue by douglasg14b** [EEParker/aspnetcore-vueclimiddleware#18]
Is one of these malicious or just a random fork? The filesizes of the DLLs are different for each.

* https://www.nuget.org/packages/extstopcode-VueCliMiddleware
  * By extstopcode, updated 5/14/2019
* https://www.nuget.org/packages/VueCliMiddleware/
  * By EEParker updated 1/7/2019

**Comment by EEParker** [comment]
I'm not sure. The source code on the package you linked points back to this repository instead of their fork. I would use caution.
