### ISSUE TITLE
.NET Core Hosting Problem

### ISSUE THREAD

**Issue by canperk** [EEParker/aspnetcore-vueclimiddleware#21]
Hello,  
I am trying to use cli middleware and getting error like : 

> The "path" argument must be of type string. Received type number.

 I will share my project folder structure below to show any hint for a solution

Here you can see the folder structure. src folder is my code base and public folder is hosting folder. 

For any reason i have place a dist folder in wwwroot but maybe is unnecessary.

![image](https://user-images.githubusercontent.com/17784391/62194986-aad9d100-b383-11e9-9b46-f07e67998561.png)

In my csproj file i have set the values as you mentioned according to my folder structure

```
<PropertyGroup>
        <SpaRoot>src\</SpaRoot>
        <DefaultItemExcludes>$(DefaultItemExcludes);node_modules\**</DefaultItemExcludes>
</PropertyGroup>
```

Any idea or fix suggestion for the solution ?

**Comment by EEParker** [comment]
Typically, the SpaRoot and all of the javascript/typescript files are in a subfolder, such as ClientApp so they don't pollute your c# project. In netcore3, I had some success with the `dist` folder being the `wwwroot` folder with no `dist` subdirectory.

The angular and react SPA templates are a good place to start. I will try to get a functional template added to this repository.

- https://github.com/aspnet/AspNetCore/tree/master/src/ProjectTemplates/Web.Spa.ProjectTemplates/content/Angular-CSharp

**Comment by canperk** [comment]
I got it and as you see my src folder is out of wwwroot like ClientApp folder. What am i missing from my side?

**Comment by canperk** [comment]
I have moved all my src and public folder to ClientApp with config files like package.json. However still getting same error. I don't know why it is putting double quotes around the port number. Hence i can not start dev server

![image](https://user-images.githubusercontent.com/17784391/62290978-5742b280-b46b-11e9-8253-6547a8b97431.png)

**Comment by EEParker** [comment]
You might try an additional `--` in your command before the arguments.
