### ISSUE TITLE
Microsoft.AspNetCore.SpaServices is being marked obsolete

### ISSUE THREAD

**Issue by EPinci** [EEParker/aspnetcore-vueclimiddleware#22]
Hello,

just for awarness, this (lifesaver!) package depends on `Microsoft.AspNetCore.SpaServices` that, with AspNetCore 3.0 is being obsoleted in favor of `Microsoft.AspNetCore.SpaServices.Extensions`.

Announcement is at: https://github.com/aspnet/Announcements/issues/379
Discussion is at: https://github.com/aspnet/AspNetCore/issues/12890

Is it worth moving to this new dependency?

Thank you.

**Comment by EEParker** [comment]
Thank you for the update. This library has been changed quite a bit for 3.0 and will probably need to change more once the upstream APIs are finalized. I will try to have all of these issues ironed out by Sept. 23.

**Comment by DLozanoNavas** [comment]
Hi! How is this going so far?

**Comment by EEParker** [comment]
This will need to switch to https://www.nuget.org/packages/Microsoft.AspNetCore.SpaServices.Extensions.

**Comment by EEParker** [comment]
FYI this was already in the code.
https://github.com/EEParker/aspnetcore-vueclimiddleware/blob/master/src/VueCliMiddleware/VueCliMiddleware.csproj#L27

**Comment by bbrandt** [comment]
To clarify, this is the dependency chain:
```
VueCliMiddleware 
      --> Microsoft.AspNetCore.SpaServices.Extensions 
            --> Microsoft.AspNetCore.SpaServices
```

If Microsoft is deprecating `Microsoft.AspNetCore.SpaServices` and keeping `Microsoft.AspNetCore.SpaServices.Extensions`, then they will need to update `Microsoft.AspNetCore.SpaServices.Extensions`.  But none of that is the concern of `VueCliMiddleware `

![image](https://user-images.githubusercontent.com/602767/78399168-07982600-75ba-11ea-84c4-34c0891de56d.png)
