### ISSUE TITLE
Either recieve "TimeoutException" or a blank page. Even though I can navigate to the port vue serve is running on and it loads the client app

### ISSUE THREAD

**Issue by douglasg14b** [EEParker/aspnetcore-vueclimiddleware#23]
**Note**: that I can run `vue serve` and the client app works as expected. Similarly when the asp.net core project is running, I can navigate to localhost:8080 and the client app loads as expected.

When I debug my asp.net application, one of two things occur:

- The page loads, and is a blank screen. No errors in console, all assets load just fine in network tab. (This happens the majority of the time)
- Perpetually shows the ` TimeoutException: The vue-cli server did not start listening for requests within the timeout period of 50 seconds. ` error. This error will persist indefinitely, despite the vue-cli app running just fine.

**The log shows:**

```
VueCliMiddleware:Information:   App running at:
  - Local:   http://localhost:8080 
  - Network: http://myip:8080 
```

**Environment:**

* VS2019
* Asp.net Core 2.2
* aspnetcore-vueclimiddleware v

**Configuration**:

```cs
            app.UseSpa(spa =>
            {
                spa.Options.SourcePath = "ClientApp";

                if (env.IsDevelopment())
                {
                    spa.UseVueCli(npmScript: "serve", port: 8080); // optional port
                }
            });
```

Why is this happening and how can I get this to work?

**Comment by douglasg14b** [comment]
Tried having VS launch chrome instead of Firefox. Chrome throws 404 at the URL (`https://localhost:44377`) opened by VS when the project is ran, any requests to that URL also throw 404. However, any requests to the api (`https://localhost:44377/api/someendpoint`) work just fine.

**Comment by douglasg14b** [comment]
Resolved by changing:

```cs
            services.AddSpaStaticFiles(configuration =>
            {
                configuration.RootPath = "ClientApp/dist";
            });
```

To:

```cs
            services.AddSpaStaticFiles(configuration =>
            {
                configuration.RootPath = "ClientApp";
            });
```

**Comment by EEParker** [comment]
I'm going to leave this open until I get some example projects posted.

**Comment by EEParker** [comment]
Sample projects are now in the repo.

**Comment by GF-Huang** [comment]
![image](https://user-images.githubusercontent.com/4510984/78595976-8bce0000-787d-11ea-8f69-d1f68f32ba4e.png)

**Comment by douglasg14b** [comment]
@GF-Huang  Why are you not making a new issue for this problem? Seems largely unrelated.
