### ISSUE TITLE
[Upstream] Specified port is completely ignored

### ISSUE THREAD

**Issue by douglasg14b** [EEParker/aspnetcore-vueclimiddleware#24]
I just upgraded my dev box, reinstalled VS, Node, and vue-cli and can no longer get my client app to run with vueclimiddleware.

It seems like the specified port is no longer used when the application actually launched. I have specified port `8080`, but it launches under a random port each time.

**Comment by douglasg14b** [comment]
Might be related to:  https://github.com/vuejs/vue-cli/issues/4452 ?

**Comment by douglasg14b** [comment]
Yep, related to that. Fix for me was:

```js
  "devDependencies": {
    "portfinder": "1.0.21"
  },
  "resolutions": {
    "@vue/cli-service/portfinder": "1.0.21"
  },
```

and run `npm install`

**Comment by EEParker** [comment]
https://github.com/http-party/node-portfinder/issues/84#issuecomment-522738475
