### ISSUE TITLE
[Upstream] Silence webpack progress

### ISSUE THREAD

**Issue by johndab** [EEParker/aspnetcore-vueclimiddleware#27]
With vue-cli 3.11.0 the progress is printed like that:

```
fail: VueCliMiddleware[0]
      <s> [webpack.Progress] 12% building 24/28 modules 4 active C:\dev\UI\node_modules\cache-loader\dist\cjs.js??ref--12-0!C:\dev\UI\node_modules\babel-loader\lib\index.js!C:\dev\UI\node_modules\eslint-loader\index.js??ref--13-0!C:\dev\UI\src\silent-renew-oidc.js


fail: VueCliMiddleware[0]
      <s> [webpack.Progress] 12% building 24/29 modules 5 active C:\dev\UI\node_modules\webpack-dev-server\node_modules\strip-ansi\index.js


fail: VueCliMiddleware[0]
      <s> [webpack.Progress] 13% building 25/29 modules 4 active C:\dev\UI\node_modules\webpack-dev-server\node_modules\strip-ansi\index.js


fail: VueCliMiddleware[0]
      <s> [webpack.Progress] 13% building 26/29 modules 3 active C:\dev\UI\node_modules\cache-loader\dist\cjs.js??ref--12-0!C:\dev\UI\node_modules\babel-loader\lib\index.js!C:\dev\UI\node_modules\eslint-loader\index.js??ref--13-0!C:\dev\UI\src\silent-renew-oidc.js


fail: VueCliMiddleware[0]
      <s> [webpack.Progress] 13% building 26/30 modules 4 active C:\dev\UI\node_modules\querystring-es3\decode.js

... and so on
```

Works fine with vue-cli 3.10.0.
VueCliMiddleware 2.2.x

**Comment by johndab** [comment]
in vue-cli 3.11 webpack emits full lines without `\b` characters and ending with `\n` so they're printed with `OnReceivedLine` like a normal messages:

![image](https://user-images.githubusercontent.com/19765124/65908614-16154300-e3c7-11e9-89df-464fec462ef7.png)

whereas in 3.10:

![image](https://user-images.githubusercontent.com/19765124/65909086-18c46800-e3c8-11e9-9b7d-044ae3816569.png)

I can't find exactly which change in webpack is responsible
Hope that helps

**Comment by EEParker** [comment]
I found a related upstream issue, so this might have to wait.
https://github.com/vuejs/vue-cli/issues/3603

**Comment by EEParker** [comment]
FYI, the current workaround is to add `chainConfig.plugins.delete('progress');` to vue.config.js

**Comment by futuralogic** [comment]
> FYI, the current workaround is to add `chainConfig.plugins.delete('progress');` to vue.config.js

Based on your comment, I tried the following, without success.

```
	chainWebpack: config => {
		config.plugins.delete('progress');
```
It doesn't seem progress plugin is in place for webpack dev server.

I was able to stop progress from being displayed by doing the following in vue.config.js:

```
module.exports = {
	devServer: {
		progress: false
	},
       ....
}
```

Info found here: https://github.com/vuejs/vue-cli/issues/4557#issuecomment-545965828

**Comment by EEParker** [comment]
Webpack progress was silenced in the sample project:

https://github.com/EEParker/aspnetcore-vueclimiddleware/blob/master/samples/VueCliSample/ClientApp/vue.config.js
