### ISSUE TITLE
.net core 3.0 is released can you Upgrade

### ISSUE THREAD

**Issue by zhaozhengyan** [EEParker/aspnetcore-vueclimiddleware#28]
.net core 3.0 is released can you Upgrade?

**Comment by douglasg14b** [comment]
Very much this.

**Comment by douglasg14b** [comment]
Oh I see, the package depends on preview versions of the framework.... that's problematic. To say the least.

**Comment by EEParker** [comment]
https://www.nuget.org/packages/VueCliMiddleware/3.0.0
