### ISSUE TITLE
Not working on 3.0

### ISSUE THREAD

**Issue by douglasg14b** [EEParker/aspnetcore-vueclimiddleware#29]
Using the new setup, on `3.0.0-preview7-1 ` I get this error:

>HttpRequestException: Failed to proxy the request to http://localhost:8080/, because the request to the proxy target failed. Check that the proxy target server is running and accepting requests to http://localhost:8080/.

The last `VueCliMiddleware` console message is: `VueCliMiddleware: Information: Starting server on port 8080...`

I can run serve commands just fine and the app runs and loads.

Also noticing that the build output does not appear in the output console in VS anymore?

**Comment by douglasg14b** [comment]
It's also leaving TONS of `Node` and `Console Window Host` instances running.

**Comment by douglasg14b** [comment]
Hm, seems the trigger for this was making changes that caused the `serve` build to fail. Even after the error was corrected and it built as expected the connection would forever hang afterwards.

Stopping the debugging didn't stop the serving it seems, and it wouldn't start on `8080` anymore.

**Comment by douglasg14b** [comment]
Actually, it looks like making ANY change that causes a rebuild triggers this.  So anytime a change is made when it's service, the app will no longer load through asp.net... It just hangs there, never returning.

This occurs with the route-based method as well as long as any of the `3.0.0-preview ` packages are being used....

Does this need to be updated to the actual .Net Core 3 release version instead of using the previews?

**Comment by douglasg14b** [comment]
Workaround for now is to use this directly:

```cs
        if (env.IsDevelopment())
        {
            spa.UseProxyToSpaDevelopmentServer(new UriBuilder("http", "localhost", 8083).Uri.ToString());
        }
```

**Comment by danijelh** [comment]
I have found the following solution online for `.NET Core 3`

Add the following code

```csharp
public static class Connection
    {
        private static int Port { get; } = 8080;
        private static Uri DevelopmentServerEndpoint { get; } = new Uri($"http://localhost:{Port}");
        private static TimeSpan Timeout { get; } = TimeSpan.FromSeconds(60);

        private static string DoneMessage { get; } = "DONE  Compiled successfully in";

        public static void UseVueDevelopmentServer(this ISpaBuilder spa)
        {
            spa.UseProxyToSpaDevelopmentServer(async () =>
            {
                var loggerFactory = spa.ApplicationBuilder.ApplicationServices.GetService<ILoggerFactory>();
                var logger = loggerFactory.CreateLogger("Vue");

                if (IsRunning())
                {
                    return DevelopmentServerEndpoint;
                }

                var isWindows = RuntimeInformation.IsOSPlatform(OSPlatform.Windows);
                var processInfo = new ProcessStartInfo
                {
                    FileName = isWindows ? "cmd" : "npm",
                    Arguments = $"{(isWindows ? "/c npm " : "")}run serve",
                    WorkingDirectory = "ClientApp",
                    RedirectStandardError = true,
                    RedirectStandardInput = true,
                    RedirectStandardOutput = true,
                    UseShellExecute = false,
                };
                var process = Process.Start(processInfo);
                var tcs = new TaskCompletionSource<int>();
                _ = Task.Run(() =>
                {
                    try
                    {
                        string line;
                        while ((line = process.StandardOutput.ReadLine()) != null)
                        {
                            logger.LogInformation(line);
                            if (!tcs.Task.IsCompleted && line.Contains(DoneMessage))
                            {
                                tcs.SetResult(1);
                            }
                        }
                    }
                    catch (EndOfStreamException ex)
                    {
                        logger.LogError(ex.ToString());
                        tcs.SetException(new InvalidOperationException("'npm run serve' failed.", ex));
                    }
                });
                _ = Task.Run(() =>
                {
                    try
                    {
                        string line;
                        while ((line = process.StandardError.ReadLine()) != null)
                        {
                            logger.LogError(line);
                        }
                    }
                    catch (EndOfStreamException ex)
                    {
                        logger.LogError(ex.ToString());
                        tcs.SetException(new InvalidOperationException("'npm run serve' failed.", ex));
                    }
                });

                var timeout = Task.Delay(Timeout);
                if (await Task.WhenAny(timeout, tcs.Task) == timeout)
                {
                    throw new TimeoutException();
                }

                return DevelopmentServerEndpoint;
            });
        }

        private static bool IsRunning() => IPGlobalProperties.GetIPGlobalProperties()
                .GetActiveTcpListeners()
                .Select(x => x.Port)
                .Contains(Port);
    }
```

And then simply call

```csharp
            app.UseSpa(spa =>
            {
                spa.Options.SourcePath = "ClientApp";

                if (env.IsDevelopment())
                {
                    //spa.UseVueCli (npmScript: "serve", port : 8080);
                    spa.UseVueDevelopmentServer(); // THIS METHOD
                }
            });
```

Work just fine with .NET 3

**Comment by 01010100010100100100100101000111** [comment]
> Using the new setup, on `3.0.0-preview7-1 ` I get this error:
> 
> > HttpRequestException: Failed to proxy the request to http://localhost:8080/, because the request to the proxy target failed. Check that the proxy target server is running and accepting requests to http://localhost:8080/.
> 
> The last `VueCliMiddleware` console message is: `VueCliMiddleware: Information: Starting server on port 8080...`
> 
> I can run serve commands just fine and the app runs and loads.
> 
> Also noticing that the build output does not appear in the output console in VS anymore?

I have everything working with the 7-1preview here, I have made the changes to output to wwwroot instead of the client-app/dist folder and also re-worked my startup to use the newer endpoint routing - everything is working OK here...

I also cloned the repo to take a look and you can just straight upgrade everything to the 3.0 packages using NuGet if you need to get it working ASAP - that also worked OK for me (was before I saw the 7-1preview package).

Using 7-1Preview I only had to change the .csproj section for the dist files to "<DistFiles Include="wwwroot\**" />" and then add the outputDir to the vue.config.js file, the Startup is just a copy-paste from the example to setup the endpoint routing, then it sprung into life for me. 

As for the console output, I have not actually seen that working since the previous version, I have been waiting for the startup timeout if there is an error, then I manually run the vue-ui build task so I can see the output - a bit of a pain but works for now, would be great to hear if anyone has any insight into the console output missing.

**Comment by EEParker** [comment]
https://www.nuget.org/packages/VueCliMiddleware/3.0.0
