### ISSUE TITLE
it’s not clear how to run the example

### ISSUE THREAD

**Issue by UseMuse** [EEParker/aspnetcore-vueclimiddleware#30]
could you make an example that you can run and see the result.
I downloaded the project, run it, and nothing happens.
the part with {* path} is not clear, what should I enter there? I write for the place {* path} - "index.html", but this does not work :(
I work with Vue Cli, for asp core 3
help me please

**Comment by EEParker** [comment]
There are two samples in the repository that run on aspnetcore 3.0
https://github.com/EEParker/aspnetcore-vueclimiddleware/tree/master/samples
