### ISSUE TITLE
Conflict with swagger

### ISSUE THREAD

**Issue by HaoZhiYing** [EEParker/aspnetcore-vueclimiddleware#31]
Hello, open the Swagger page and go to the single page of the Vue cli process. I don't know why this is.

**Comment by EEParker** [comment]
You might have to change the order of your Use[Middleware]() functions or wrap it in a Map or MapWhen(). Aspnetcore processes the first middleware that matches the url, so order matters.

**Comment by HaoZhiYing** [comment]
OK, thank you
