### ISSUE TITLE
Node Process Not Being Killed

### ISSUE THREAD

**Issue by PrinceManfred** [EEParker/aspnetcore-vueclimiddleware#33]
I'm having an issue with node processes from previously stopped debug sessions not being killed on next launch. I submitted pull request #32 to allow you to optionally specify a force kill option (which fixed my issue) but was told it's good form to open an issue along with it. Is there possibly something I'm missing? Thanks for the great work!

**Comment by edvinkuric** [comment]
Hey @PrinceManfred @EEParker,

i have the same problem too - would be great if you could review the pull request for this (i'm using ASP.NET Core 2.2)

Thanks for the great work too, i appreciate it!

**Comment by elmercd** [comment]
I also noticed that the node process is not being killed when I restart the application, causing Vue CLI to use a different port. Now the middleware will keep hooking in to the previous/default port and hot-reload will not work. I've tried cloning @PrinceManfred's update locally and I think so far it works (I'm using ASP.NET CORE 3.0).

@EEParker I think you should take a look at his PR.
I really like how easy it is to integrate Vue with ASP.NET Core with this middleware.

Thanks!

**Comment by EnsPzr** [comment]
I live same problem.
