### ISSUE TITLE
index.html?

### ISSUE THREAD

**Issue by rothariger** [EEParker/aspnetcore-vueclimiddleware#36]
Hi,

excellent work with this tool, i'm using this in an old project with net core 2.2, but now i'm having issues implementing it with core 3.1.

i'm creating a new project, it's brand new, the thing is that i don't have a index file at the root, the only index file is at ClientApp/dist/index.html and when i deploy the project to a IIS server, it doesn't work, it says that it couldn't find any index.html.

any suggestion?

Regards.

**Comment by renanrcp** [comment]
It's because vue publishes on dist, not in wwwroot, it's much easier for you to work around this by moving ASP.Net Core redirect than vue:
`
if (env.IsDevelopment())
                {
                    endpoints.MapToVueCliProxy(
                    "{*path}",
                    new SpaOptions { SourcePath = "ClientApp" },
                    "serve",
                    8080,
                    ScriptRunnerType.Npm,
                    "Compiled successfully");
                }
                else
                {
                    endpoints.MapFallbackToFile("ClientApp/dist/index.html", new StaticFileOptions
                    {
                        ServeUnknownFileTypes = true,
                        FileProvider = new PhysicalFileProvider(Directory.GetCurrentDirectory())
                    });
                }
`

**Comment by rothariger** [comment]
i get it working removing the mapfallbacktofile and put the old usespa...

`app.UseSpa((spa) =>
            {
                spa.Options.SourcePath = "ClientApp";
            });`

**Comment by EEParker** [comment]
I have updated the samples to reflect SPA static file usage.
