### ISSUE TITLE
Official example for Production environments

### ISSUE THREAD

**Issue by nixxholas** [EEParker/aspnetcore-vueclimiddleware#40]
Hi there,

Really sorry for asking this but it'll be great if there's an official sample for production environments so that everyone can stick to the right practice you deem fit.

Comments at https://github.com/EEParker/aspnetcore-vueclimiddleware/blob/master/samples/VueCliSample/Startup.cs clearly explain the need to use the proper static files DI together with a proper webpack dist. Would be good to have an actual example.

**Comment by EEParker** [comment]
I have updated the samples and readme to reflect proper production usage.
