### ISSUE TITLE
Launch IIS Error .net core 3.1

### ISSUE THREAD

**Issue by EnsPzr** [EEParker/aspnetcore-vueclimiddleware#44]
![image](https://user-images.githubusercontent.com/18161640/74232625-3db3da80-4cda-11ea-9c17-a2d94986d119.png)

Hello. In order to work on virtual directories, I created my own site in local iis and linked my project there. When I run it in development mode, I get the error in the picture. But it works when I run it in production mode. Of course, the changes I made in the project do not appear on the screen since it is in production mode.

![image](https://user-images.githubusercontent.com/18161640/74232866-aa2ed980-4cda-11ea-8450-febcf7340db9.png)

**Comment by EEParker** [comment]
It looks like NPM did not run webpack dev server. Make sure nothing is bound to port 8080. You might have to terminate any other nodejs processes.

**Comment by EnsPzr** [comment]
Yes. I tried this. But again I encountered the same problem.

**Comment by EEParker** [comment]
To run in a virtual directory, make sure to specify app.UsePathBase("/virtualdirectory/"); in your Startup.cs Configure method. The webpackdevserver still runs at the root "/" , so you need to use MapWhen or some routing technique to make sure you are sending the correct URL to the UseVluCli proxy. In production, it will add a <base > tag so it isn't an issue there.

**Comment by EnsPzr** [comment]
Okey. Thank you :)
