### ISSUE TITLE
.NET Core 3.1 migration, still need app.UseSpa()

### ISSUE THREAD

**Issue by DavidDeSloovere** [EEParker/aspnetcore-vueclimiddleware#45]
Hi,

I'm having issues with a migration from 2.0 to 3.1 running in "production" mode.
A call to `app.UseSpa()` is still required, or the client files are not served. Is this expected behaviour?

I have `app.UseSpaStaticFiles();` and `services.AddSpaStaticFiles(opt => { opt.RootPath = "ClientApp/dist"; });` like the readme says.

Does it have something to do with wwwroot? I don't really understand what is meant by this from the readme:
`First, be sure to switch Vue Cli or Quasar Cli to output distribution files to wwwroot directly (not dist).`

Both `MapToVueCliProxy` and the old `UseProxyToSpaDevelopmentServer` work perfectly in "development" mode.

**Comment by EEParker** [comment]
`services.AddSpaStaticFiles(opt => { opt.RootPath = "ClientApp/dist"; });` will expect the webpack output, typically index.html + images + css to be in the folder ClientApp/dist. ClientApp would be a sibling directory of wwwroot, not nested. 

The comment 'First, be sure to switch Vue Cli or Quasar Cli to output [...]' was a remnant from some pre-release AspNetCore 3.0-previewX and probably needs to be removed from the readme file.

**Comment by marisks** [comment]
While `services.AddSpaStaticFiles` will serve static files correctly, application routing without `MapToVueCliProxy` does not work.

How to correctly configure the app for the production so that routing works? 

By routing, I mean that there is, for example, a route `/companies` in the Vue app.
When `MapToVueCliProxy` is enabled and I refresh the page with route `/companies`, the app is loaded and everything works correctly.
But when `MapToVueCliProxy` disabled, `/companies` returns 404. I can go to the root of the app `/` and then navigate to `/companies` without any issues. Refresh and get 404.

`app.UseSpa` seems working, but is it right to use it?

**Comment by EEParker** [comment]
In our applications this is what we use:

```csharp
	public virtual void ConfigureServices(IServiceCollection services)
	{
		services.AddControllers();
		
		// Load static generated files from disk
		services.AddSpaStaticFiles(configuration => configuration.RootPath = "ClientApp/dist");
	}

	public virtual void Configure(IApplicationBuilder app, IWebHostEnvironment env)
	{
		// optional base path for IIS virtual app/directory
		app.UsePathBase("/optionalpath");
		
		// production SPA static files
		app.UseSpaStaticFiles();
		
		// wwwroot static files
		app.UseStaticFiles();
		
		// aspnetcore routing/auth/etc
		app.UseRouting();
		app.UserAuthorization();
		app.UseEndpoints(endpoints =>
		{
		   // add controllers
		   endpoints.MapControllers();
		   
		   // add OData
		   endpoints.EnableDependencyInjection();
		   endpoints.Select().Filter().OrderBy().Count().MaxTop(100);
		   endpoints.MapODataRoute("odata", "odata", BuildOdataModel());

		   // add vue
		   endpoints.MapToVueCliProxy(
			   "{*path}",
			   new SpaOptions { SourcePath = "ClientApp" },
			   npmScript: (System.Diagnostics.Debugger.IsAttached) ? "serve" : null,
			   forceKill: true);
		});
    }
```

**Comment by fuzzzerd** [comment]
The readme file states to put the call to `MapToVueCliProxy` inside an `#IF ` block, 

> ```
> // NOTE: VueCliProxy is meant for developement and hot module reload
> // NOTE: SSR has not been tested
> // Production systems should only need the UseSpaStaticFiles() (above)
> // You could wrap this proxy in either
> // if (System.Diagnostics.Debugger.IsAttached)
> // or a preprocessor such as #if DEBUG
> ```

The sample above doesn't have that gate, and always calls `MapToVueCliProxy` and without that call, visiting `https://localhost:####/` gives an empty page. Manually typing `https://localhost:####/index.html` does work.

I checked the source and found that the check in your sample `npmScript: (System.Diagnostics.Debugger.IsAttached) ? "serve" : null,` causes the internals to basically call `app.UseSpa` as expected, but skips the `UseVueCli` when `npmScript` is null. 

@EEParker Can you provide any guidance on what a production startup.cs would look like? The current readme seems to offer conflicting advise; despite the fact that it looks like it may be safe as-is?

**Comment by EEParker** [comment]
I have updated the readme to reflect my comments here. This is what we are using in production applications hosted in IIS. Other deployment methods may require different configuration. https://github.com/EEParker/aspnetcore-vueclimiddleware/issues/45#issuecomment-614354233

**Comment by fuzzzerd** [comment]
Thanks. To be clear with that setup, we're depending on MapToVueCliProxy to continue to branch on the `npmScript` parameter? 

Meaning if if there is an `npmScript` it will setup the web pack dev server proxy via `npm run serve` but if its null, it skips that, but still calls `UseSpa`?

It would be nice if there were a more explicit option, because the recommended setup has issues with serving local files, integrating Swashbuckle, because internally MapToVueCliProxy uses a catch all fallback route which screws up the path/routing of those other static files.

**Comment by lisenz** [comment]
@fuzzzerd 
Hi, I have the same problem. in development mode, there was no problem,but there was a problem after publishing.
Did you solve your problem?

**Comment by fuzzzerd** [comment]
I haven't gotten it working both locally and published. No matter what I did, one would work and the other would fail.

**Comment by bryandam** [comment]
I was able to get this to working in debug, release, and published.  Here's the pseudo-code for my startup file based on the project's sample:

```
public void ConfigureServices(IServiceCollection services)
{
	// NOTE: Ensure this is the same path that is specified in your webpack output
	if (!System.Diagnostics.Debugger.IsAttached)
	{
		services.AddSpaStaticFiles(opt => opt.RootPath = "ClientApp/dist");
	}
	services.AddControllers();
}

public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
{
	if (env.IsDevelopment()) {app.UseDeveloperExceptionPage();}

	// NOTE: this is optional, it adds HTTPS to Kestrel
	app.UseHttpsRedirection();
	app.UseStaticFiles();

	// In production use the static SPA files that VueCli built when the project is published.
	if (!System.Diagnostics.Debugger.IsAttached) {app.UseSpaStaticFiles();}   

	app.UseRouting();
	app.UseAuthentication();
	app.UseAuthorization();

	app.UseEndpoints(endpoints =>
	{
		endpoints.MapControllers();

		// If debugging, connect to the VueCliMiddleware proxy.
		if (System.Diagnostics.Debugger.IsAttached) { 
			endpoints.MapToVueCliProxy(
				   "{*path}",
				   new SpaOptions { SourcePath = "ClientApp" },
				   npmScript: "serve",
				   forceKill: true
				);
		}
	});
	
	// If note debugging, use the static spa files.
	if (!System.Diagnostics.Debugger.IsAttached){app.UseSpa(spa => {spa.Options.SourcePath = "ClientApp";});}
}
```

**Comment by jaybo** [comment]
Something else to possibly include in Readme.md, since this may be the source of many similar SPA problems.  If routing isn't working, check your Vue/Quasar app code. You may need to add additional routes, since in Quasar sample code they're not enabled by default.  In `ClientApp/src/router/routes.js` expand the `path` from` '/'` to` '/*'`.

```
const routes = [
  {
    path: '/*',  // added the asterisk!
    component: () => import('layouts/MainLayout.vue'),
    children: [
      { path: '', component: () => import('pages/Index.vue') },
    ]
  }
]
```

**Comment by VictorioBerra** [comment]
Same issue here with Nuxt. I followed the samples perfectly and running in debug mode works great.

Running in release: I have to manually navigate to /index.html otherwise I get a 404 from ASPNET Core.

**Comment by VictorioBerra** [comment]
This seems to work for me 

```csharp
public virtual void ConfigureServices(IServiceCollection services)
{
    services
        .AddCustomSpaStaticFiles()
        .AddControllers();
}

/// <summary>
/// Configures the application and HTTP request pipeline. Configure is called after ConfigureServices is
/// called by the ASP.NET runtime.
/// </summary>
/// <param name="application">The application builder.</param>
public virtual void Configure(IApplicationBuilder application) =>
    application
        .UseIf(!this.webHostEnvironment.IsDevelopment(), devApp => devApp.UseCustomSpaStaticFiles())
        .UseStaticFiles()
        .UseRouting()
        .UseEndpoints(
            builder =>
            {
                var controllerBuilder = builder
                    .MapControllers();

#if DEBUG
                // NOTE: VueCliProxy is meant for developement and hot module reload
                // NOTE: SSR has not been tested
                // Production systems should only need the UseSpaStaticFiles() (above)
                // You could wrap this proxy in either
                // if (System.Diagnostics.Debugger.IsAttached)
                // or a preprocessor such as #if DEBUG
                builder.MapToVueCliProxy(
                    "{*path}",
                    new SpaOptions { SourcePath = "ClientApp" },
                    npmScript: System.Diagnostics.Debugger.IsAttached ? "dev" : null,
                    regex: "Compiled successfully",
                    forceKill: true);
#endif

            })
            .UseSpa(spa =>
            {
                spa.Options.SourcePath = "ClientApp";
            });
```

In the end it came down to calling `UseSpa` at the end in addition to UseCustomSpaStaticFiles (only when in prod). Nuxt config did not require any changes.

Hope this helps someone else.
