### ISSUE TITLE
How to run from command line?

### ISSUE THREAD

**Issue by dotnetshadow** [EEParker/aspnetcore-vueclimiddleware#46]
**FIXED**
Found the errors, I noticed in `startup.cs` there was a line 
`npmScript: (System.Diagnostics.Debugger.IsAttached) ? "serve" : null,` 
I just had to remove the condition and set it to "serve"
 

Firstly thank you for your great project outstanding work!

I was trying the **VueCliSample** in visual studio I can press debug and everything seems to work correctly.

**Command Line**
From command line  I run ```dotnet watch run``` and `npm run serve` but I get the error message: `The SPA default page middleware could not return the default page '/index.html' because it was not found, and no other middleware handled the request.`

So I'm wondering what the command line should be?

Thanks for your time and effort

**Comment by EEParker** [comment]
That is good to note. I'll leave this issue open until the samples are updated. I think there is some comments in the samples that state it should also be possible to use preprocessor directives such as `#if debug` instead of the `Debugger.IsAttached`.
