### ISSUE TITLE
How can I run the vue process externally?

### ISSUE THREAD

**Issue by evolvedlight** [EEParker/aspnetcore-vueclimiddleware#47]
Hi,

I have a standard asp.net core 3.1 app with vue.js. It's using this to serve the clientapp with hot reload.
However many of the changes I need to make mean that I need to restart the c# side, which also means I have to wait 30 seconds for the vue.js app to compile.

Is there any way to connect to an already running instance of npm serve? I'd like to be able to run it separately so I don't wait so long each time. If it's possible but not documented or implemented, I'm happy to try to contribute a PR. 

Thanks,
Steve

**Comment by EEParker** [comment]
That scenario would be covered by the default UseProxyToSpaDevelopmentServer instead of this middleware. You can manually launch your web app with `npm server` or the command you have set up.

**Comment by evolvedlight** [comment]
Great, thanks very much :)
