### ISSUE TITLE
CORS Support

### ISSUE THREAD

**Issue by EEParker** [EEParker/aspnetcore-vueclimiddleware#5]
On behalf of @Ethan0007

Hi,

I would like to ask any idea about on how can i enable CORS on this setup?
I already added addCors in my configureservice:
![image](https://user-images.githubusercontent.com/15874076/51208270-d2c78280-18d2-11e9-8998-422366455f0e.png)

and UserCors in Configure:
image
![image](https://user-images.githubusercontent.com/15874076/51208281-d78c3680-18d2-11e9-8e96-0b59725c9e8c.png)

But when i put my script in separate server i still got this issue:
image
![image](https://user-images.githubusercontent.com/15874076/51208294-dbb85400-18d2-11e9-96fe-da759559c01f.png)

this is my request:
image
![image](https://user-images.githubusercontent.com/15874076/51208301-df4bdb00-18d2-11e9-8d79-55a38bde6d84.png)

this my controller:
image
![image](https://user-images.githubusercontent.com/15874076/51208308-e377f880-18d2-11e9-883b-bd14c6e85acb.png)

Thanks!

**Comment by Ethan0007** [comment]
I already solved the issue by changing the request header from axios.
