### ISSUE TITLE
I think forcekill should be true by default

### ISSUE THREAD

**Issue by changetocoding** [EEParker/aspnetcore-vueclimiddleware#51]
Had an issue where running a different solution using this library served pages from the previous solution (also using this library). 

After a bit of confusion and manually killing the node processes realised that forcekill parameter on MapToVueCliProxy resolves this.

Would agree that this should be true by default to prevent my silly mistake. Thoughts?

**Comment by EEParker** [comment]
Agreed. I will make this change.
