### ISSUE TITLE
HTTPS Support

### ISSUE THREAD

**Issue by T0shik** [EEParker/aspnetcore-vueclimiddleware#54]
The main issue is if the dotnet core app is using https and vue isn't the hot reload doesn't work.

It's possible to setup vue-cli to work with https, I've added the option to set https & added instructions to the `README.md` on how to generate certificates for the dev server. #53 

Just note that having a dev environment being https is important to move the bar. it's 2020 like cmon why is security not the default yet.

**Comment by EEParker** [comment]
Thank you for the PR!

**Comment by T0shik** [comment]
Awesome! Thank you for the library btw!
