### ISSUE TITLE
Https options not available in NuGet

### ISSUE THREAD

**Issue by AdrianoAE** [EEParker/aspnetcore-vueclimiddleware#58]
Hello, the https option in MapToVueCliProxy is not available in the most recent NuGet package.

**Comment by bryandam** [comment]
Can confirm.  I'd add that it probably makes sense to have the samples rely on the NuGet package instead of a project dependency.  They'd become good starter templates.

**Comment by Kingside88** [comment]
Also wsl is not there

**Comment by EEParker** [comment]
This should be live on nuget as version 3.1.2, thanks.
