### ISSUE TITLE
For .net core 3

### ISSUE THREAD

**Issue by hnviradiya** [EEParker/aspnetcore-vueclimiddleware#6]
.Net core 3 is still in preview mode. So are we going to wait till then?

**Comment by EEParker** [comment]
I will probably wait for an RC before doing any updates. netcore3 is still undergoing heavy changes.

**Comment by enginkirmaci** [comment]
Hi @EEParker , I forked this repo and updated it to 3.0.0-preview5. anyone who wants to try 
https://github.com/enginkirmaci/aspnetcore-vueclimiddleware

**Comment by EEParker** [comment]
@enginkirmaci Thanks! I pulled your change for the logger and pushed a 3.0.0-preview6 version to nuget.

https://github.com/EEParker/aspnetcore-vueclimiddleware/releases/tag/3.0.0-preview6
