### ISSUE TITLE
Why recommend endpoint routing?

### ISSUE THREAD

**Issue by fuzzykiller** [EEParker/aspnetcore-vueclimiddleware#71]
This is entirely a question. First, this is what I get with `dotnet new angular` in ASP.NET Core 3.1:

```cs
// other stuff before this
if (!env.IsDevelopment())
{
    app.UseSpaStaticFiles();
}

app.UseRouting();

app.UseEndpoints(endpoints =>
{
    endpoints.MapControllerRoute(
        name: "default",
        pattern: "{controller}/{action=Index}/{id?}");
});

app.UseSpa(spa =>
{
    // To learn more about options for serving an Angular SPA from ASP.NET Core,
    // see https://go.microsoft.com/fwlink/?linkid=864501

    spa.Options.SourcePath = "ClientApp";

    if (env.IsDevelopment())
    {
        spa.UseAngularCliServer(npmScript: "start");
    }
});
```

The way I see it, using endpoint routing in this middleware doesn’t bring any benefits for common use cases. However, it adds quite some confusion by deviating from established patterns. I understand that it enables advanced use cases like requiring authentication for the SPA.

I think the recommended configuration should still be `UseVueCli`.

**Comment by EEParker** [comment]
At the time of publishing, Microsoft was pushing Endpoint Routing.  I would suggest using whatever fits your project, as we are using both routing types in our projects.

**Comment by BinarySpike** [comment]
How to I remove the authentication required?  It's requiring authentication for my source-maps, which `vscode` doesn't provide when it attaches to the chrome debugger.
