### ISSUE TITLE
HMR Works But Page Doesn't Reload

### ISSUE THREAD

**Issue by bryandam** [EEParker/aspnetcore-vueclimiddleware#72]
I have VueCliMiddleware mostly working in our app with one small exception: it doesn't automatically refresh the page.  When I save a Vue file I can see in the output that vue/webpack has recompiled the app but the page doesn't automatically refresh.  If I manually refresh the changes appear just fine.

The sample application works and I used the code from it's startup class and project file. Any thoughts on where that disconnect might be or what to look at?

**Comment by Kingside88** [comment]
Do you created an certifikate with the mkcert tool?
https://github.com/EEParker/aspnetcore-vueclimiddleware

**Comment by bryandam** [comment]
Thanks @Kingside88 and sorry for the delay.  Had to fight a different fire for a week there.

I matched the VueCliSample to match my project (https/same ports) and was unable to reproduce the issue.  Neither projects were enabling HTTPS in the VueCliProxy.  Though I went through and enable it in both and still get the same behavior: VueCliSample will properly refresh the page while my own project will not.  To do that though I had to copy over the VueCliMiddleware code directly into my project because the latest code which includes the HTTPS  property hasn't been uploaded to NPM.

Since I had the code I figured I'd try and see what's going on here.  I suspect there's some kind of timing issue here.  If I start debugging the VueCliMiddleware project I can make VueCliSample fail in a similar way.  For instance, put a breakpoint in Internal's Run's while loop and walk through that when a Vue file is updated ... the SPA is recompiled but the page update doesn't trigger.

**Comment by deep8317** [comment]
@bryandam Where did you store SSL certificate and key for your dev environment?

I put them in the same directory as **ClientApp**, and updated **vue.config.js** as below: 
`const fs = require('fs');
module.exports = {
    devServer: {
        https: {
            key: fs.readFileSync('localhost+3-key.pem'),
            cert: fs.readFileSync('localhost+3.pem'),
        }
    }
};`

This has been working well so far. However, I am pointing to VueCliMiddleware manually for now.

**Comment by TobbenTM** [comment]
@bryandam 
I made a PR to make this experience better here: #74

If you want to use this before it gets merged and released, you can simply update your Vue CLI to a recent version, and add the following environment variable:

![image](https://user-images.githubusercontent.com/1180644/95963595-2c424580-0e08-11eb-901c-157fe8ce5fd8.png)

**Comment by bryandam** [comment]
@deep8317 I initially had them in my documents folder so I could share them between the sample projects and my own.  I moved them as you suggested but that didn't change the behavior.

@TobbenTM I grabbed the code from your fork and can confirm that HMR now works in my project without having to run vue-cli in HTTPS mode.  Thanks so much for improving that!

**Comment by EEParker** [comment]
This should be live on nuget as version 3.1.2, thanks.

**Comment by bryandam** [comment]
Awesome, thanks @EEParker!  Glad you were able to get that out so quickly.
