### ISSUE TITLE
[Querstion] Authorization HowTo

### ISSUE THREAD

**Issue by Kingside88** [EEParker/aspnetcore-vueclimiddleware#83]
Hi there,
is it possible to implement somehow authorization in ASP .NET Application?
I mean between the request arrives and forwarded to the proxy. 
Best regards

**Comment by EEParker** [comment]
Yes, middleware are executed sequentially so you can add a app.UseAuthorization() before the call to this middleware. See https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/?view=aspnetcore-5.0#middleware-order for more details.
