### ISSUE TITLE
Quasar template only support typescript?

### ISSUE THREAD

**Issue by besley** [EEParker/aspnetcore-vueclimiddleware#85]
Hi, thanks your project, there is a quesiton, if the developer want to support javascript rather than typescript, it seemed that some configuration file will be changed.

**Comment by BinaryConstruct** [comment]
These templates are meant to be used as an example only. The ClientApp section can be completely replaced by using the quasar cli new project function.

**Comment by EEParker** [comment]
The ClientApp folders can be replaced in their entirety by using the vue-cli or quasar-cli generators. The important changes are all done to the csharp projects.
