### ISSUE TITLE
Https support

### ISSUE THREAD

**Issue by dyesdyes** [EEParker/aspnetcore-vueclimiddleware#9]
Hey,

I enabled https, even in local yes and I get a lot of the following :

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://192.168.1.18:8085/sockjs-node/info?t=1549978713174. (Reason: CORS request did not succeed)

The thing is that even it wasn't blocked, it wouldn't be correct as it seems like the spa listens on http 8085 only, not https.

Here is a bit of my StartUp.cs:

            app.UseHttpsRedirection();
            app.UseStaticFiles();
            app.UseSpaStaticFiles();
            app.UseSpa(spa =>
            {
                spa.Options.SourcePath = "ClientApp";

                if (env.IsDevelopment())
                {
                    spa.UseVueCli(npmScript: "serve", port: 8085);
                }
            });

What should I do?

On mozilla

![screenshot](https://user-images.githubusercontent.com/1426272/52639599-e87d9700-2ed4-11e9-83ce-a15cdc09abf2.png)

On chrome
![screenshot 2](https://user-images.githubusercontent.com/1426272/52640184-30e98480-2ed6-11e9-85ce-7759b91bc700.png)

**Comment by TobbenTM** [comment]
Until this middleware has been fixed or the Vue CLI has been improved, you need to set the public url for the vue dev server:

```js
// vue.config.js
module.exports = {
    devServer: {
        public: 'https://localhost:44393/'
    }
};
```

Where the "public" value is the url to your ASP.Net application. This makes the HMR client use the ASP.Net proxy instead of trying to connect directly to the webpack dev server using the wrong protocol.

**Comment by clement-fifty** [comment]
Thanks, it works :)

Note that in my case 'https://localhost:44393/' didn't work but 'https://localhost:44393' (no trailing '\') did.

**Comment by MarkSky** [comment]
I have set the vue.config.js:
```
module.exports = {
    devServer: {
        headers: {
            'Access-Control-Allow-Origin': '*',
            'Access-Control-Allow-Methods': '*',
            'Access-Control-Allow-Headers': '*',
        },
        https: true,
        public: 'https://localhost:44310/',
    },
};
```
But I still got the error: 

> sockjs.js:1606 GET https://10.10.0.10:8080/sockjs-node/info?t=1574842713050 net::ERR_SSL_PROTOCOL_ERROR

How should I do to solve the error?
